export const APP_LOAD = "APP_LOAD"

export const CONFIGURATION_LOAD = "CONFIGURATION_LOAD"
export const CONFIGURATION_LOAD_OK = "CONFIGURATION_LOAD_OK"
export const CONFIGURATION_LOAD_KO = "CONFIGURATION_LOAD_KO"

export const LIST_REFRESH = "LIST_REFRESH"
export const LIST_LOAD = "LIST_LOAD"
export const LIST_LOAD_OK = "LIST_LOAD_OK"
export const LIST_LOAD_KO = "LIST_LOAD_KO"

export const DETAIL_REFRESH = "DETAIL_REFRESH"
export const DETAIL_LOAD = "DETAIL_LOAD"
export const DETAIL_LOAD_OK = "DETAIL_LOAD_OK"
export const DETAIL_LOAD_KO = "DETAIL_LOAD_KO"

export const SEARCH_LOAD = "SEARCH_LOAD"
export const SEARCH_LOAD_OK = "SEARCH_LOAD_OK"
export const SEARCH_LOAD_KO = "SEARCH_LOAD_KO"